#resilience4j.circuitbreaker:
#    configs:
#      default:
#        slidingWindowSize: 100
#        permittedNumberOfCallsInHalfOpenState: 10
#        waitDurationInOpenState: 10000
#        failureRateThreshold: 60
#        eventConsumerBufferSize: 10
#        registerHealthIndicator: true
#    instances:
#      backendA:
#        baseConfig: default