server:
  port: 0

spring:
  application:
    name: my-second-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    stream:
      bindings:
        send-out-0:
          destination: bookChange
          content-type: application/json
          producer:
            requiredGroup: bookChange
      kafka:
        binder:
          brokers: 127.0.0.1
          auto-create-topics: true
      default-binder: kafka

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        integration: DEBUG