logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    me.study: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: authenticationservice
  profiles:
    active:
      default

server:
  servlet:
    contextPath: /auth
  port: 8901
