server:
  port: 8081

spring:
  application:
    name: my-first-service
  profiles:
    active: default

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,refresh