server:
  port: 8081

spring:
  application:
    name: first-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  config:
    import: "configserver:http://localhost:8888"
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    stream:
      bindings:
        sink-in-0:
          destination: book-change-topic
          content-type: application/json
          group: bookGroup
        send-out-0:
          destination: book-change-topic
          content-type: application/json
          group: bookGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
      default-binder: kafka

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.example.firstservice: DEBUG


---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://127.0.0.1:8901/auth/user # jwt 토큰 검증 url 로 변경 필요
